version: "3.8"
services:
  outcome_frontend:
    container_name: outcome_frontend
    image: armankhanx123/service_1
    build: ./service_1
    ports: 
    - target: 5000
      published: 80
      protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI}

  player_backend:
    container_name: football_player_backend
    image: armankhanx123/service_2
    build: ./service_2

  team_backend:
    container_name: football_team_backend
    image: armankhanx123/service_3
    build: ./service_3

  result_backend:
    container_name: football_result_backend
    image: armankhanx123/service_4
    build: ./service_4
